name: Pytest

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
          cache: true

      - run: pixi run test
