name: Linting and tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Ruff linting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Runs Ruff lint checking
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
          cache: true
      - run: pixi run lint
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Runs Pytest
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
          cache: true
      - run: pixi run test
